### ISSUE TITLE
Unable to access bucket 

### ISSUE THREAD

**Issue by nona00** [sillygoose/multisma2#1]
Hello,

I want to use multisma2 with InfluxDB 1.8.4

I created a database multisma2 with user multisma2, but I get the following error:

python3 multisma2.py
[2021-03-21 19:54:28,429] [logfiles] [INFO] Created application log at log/multisma2.log
[2021-03-21 19:54:28,437] [multisma2] [INFO] multisma2 inverter collection utility 1.0.0.dev, PID is 17375
[2021-03-21 19:54:28,441] [influx] [ERROR] Unable to access bucket 'multisma2/autogen' at http://127.0.0.1:8086
[2021-03-21 19:54:28,441] [multisma2] [CRITICAL] Received FailedInitialization exception detected
[2021-03-21 19:54:28,442] [multisma2] [INFO] Closing multisma2 application
[2021-03-21 19:54:28,442] [influx] [INFO] Closed the InfluxDB bucket 'multisma2/autogen

 ;# InfluxDB setup
 ; # The InfluxDB interface uses the newer 2.0 client which supports both the 2.0 and 1.8.x InfluxDB versions
 ; # with just minor changes in the configuration making a future upgrade to v2 a simple change of options.
 ; #
 ; # Influxdb configuration options:
 ; #   influxdb2.enable        set to True to enable InfluxDB output, False to disable output
 ; #   influxdb2.bucket        set to the InfluxDB bucket (v2) or 'database/retention_policy' (v1.8)
 ; #   influxdb2.url           set to the InfluxDB server URL and port
 ; #   influxdb2.org           set to the v2 organization or '-' if using v1.8.x
 ; #   influxdb2.token         set to a valid v2 token or v1.8.x 'username:password'
  influxdb2:
    enable: True
    url: 'http://127.0.0.1:8086'
    bucket: 'multisma2/autogen'
    org: '-'
    token: 'multisma2:password'

How can the retention policy specified?

How can a bucket be created in InfluxDB 2.0?

**Comment by sillygoose** [comment]
Try using the IP address of the InfluxDB server.  I had a similar problem on my home network and testing now with InfluxDB2 I get the following results:

Works: url: 'http://192.168.1.81:8086'
Works: url: 'http://dundee.local:8086'
Fails: url: 'http://localhost:8086'
Fails: url: 'http://127.0.0.1:8086'

If that doesn't help I will install the old version of InfluxDB and try it out. Since I switches to InfluxDB2 I added code that does a query to confirm the database is accessible and that is the error you are seeing.

> How can the retention policy specified?

What you have is the default retention policy so should work if it matches what you see in Chronograf.

> How can a bucket be created in InfluxDB 2.0?

In InfluxDB2 there is no Chronograf so you just log into database UI at port 8086 and you can create databases and explore the data.  I suppose you could also do it from the command line but do everything in the UI.

**Comment by sillygoose** [comment]
Any results resolving this?

**Comment by nona00** [comment]
Thank you for the hint. I got it started by using 'http://192.168.1.3:8086' and uncommenting the following line in influx.py:

query_api.query(f'from(bucket: "{self._bucket}") |> range(start: -1m)')

Perhaps it fails when the bucket is empty?

[2021-03-26 01:27:18,240] [logfiles] [INFO] Created application log at log/multisma2.log
[2021-03-26 01:27:18,248] [multisma2] [INFO] multisma2 inverter collection utility 1.0.0.dev, PID is 12520
[2021-03-26 01:27:18,250] [influx] [INFO] Connected to the InfluxDB database at http://192.168.1.3:8086, bucket 'multisma2'
[2021-03-26 01:27:19,652] [pvsite] [INFO] Dawn occurs at 05:49, noon is at 12:38, and dusk occurs at 19:26 on this 85th day of 2021

I see writes in the influxdb logfile:
Mar 26 01:39:00 debian influxd[12276]: [httpd] 192.168.1.3 - - [26/Mar/2021:01:39:00 +0100] "POST /api/v2/write?org=-&bucket=multisma2&precision=s HTTP/1.1" 204 0 "-" "influxdb-client-python/1.15.0" a835669c-8dcb-11eb-8018-901b0e659723 5691

Now I upgraded to InfluxDB 2.0, but it seems that not all data is logged.

**Comment by nona00** [comment]
attached grafana screenshot

**Comment by nona00** [comment]
![grafana_multisma2](https://user-images.githubusercontent.com/3192606/113492844-ea52ac00-94da-11eb-90e8-e1868fc3261d.PNG)

**Comment by sillygoose** [comment]
I'll look at the query test as it was added much later, the idea was to know right away that the database was accessible when first connecting and not find out when the first write was attempted.

As for the Grafana dashboard I would prefer to examine the database in the InfluxDB Data Explorer first to confirm the data is being pulled from the inverter(s).  You are getting sun position and irradiance data but this is created within multisma2.  Have you looked at the multisma2 log for any errors?

This is what I see when I look at the database with the InfluxDB2 Data Explorer:

![data-explorer](https://user-images.githubusercontent.com/758224/113497534-24b84b00-94d3-11eb-921a-1346aeba5e42.jpg)

**Comment by sillygoose** [comment]
Tested this on InfluxDB2 (specifically 2.0.4) and I could not get the query test to fail with a new empty bucket, the only way I could trigger a failure was specify a non-existent bucket, a bad access token, or a bad organization.

Any ideas on how I can pursue this?

**Comment by nona00** [comment]
sorry for my late reply. Now I re-installed InfluxDB2, created a new bucket multisma2 and got the board working in InfluxDB. But data is missing:
![multisma2_influxdb](https://user-images.githubusercontent.com/3192606/123605418-180a7100-d7fc-11eb-8441-7186ec02f320.PNG)
![multisma2_grafana](https://user-images.githubusercontent.com/3192606/123605427-1b056180-d7fc-11eb-9289-3b638eb6e339.PNG)

**Comment by sillygoose** [comment]
It looks like you have data in the database as the clear sky, status, and inverter output show results in the InfluxDB2 dashboard, perhaps you have a problem with Grafana pulling the data out of InfluxDB2?

**Comment by sillygoose** [comment]
Open a new issue if there are problems since there has been nothing for a few months.
