### ISSUE TITLE
On the Grid usage

### ISSUE THREAD

**Issue by tunavis** [sillygoose/multisma2#2]
Good day ,

Is it possible to view the Grid usage compared to the current solar Usage?

**Comment by sillygoose** [comment]
No, my system doesn't support any load numbers, just solar production.

Also I stopped using this as of1/1/2023 and now use the Home Assistant SunnyBoy support as it supports multiple inverters and allows me to integrate my load data.  I recommend you check it out.

**Comment by tunavis** [comment]
Thanks does it support sma inverters?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
Yes
